# Generated by Django 5.0.2 on 2024-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_show_in_index_article_first_level_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
