# Generated by Django 5.0.2 on 2024-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Picture'), ('V', 'Video'), ('R', 'Report'), ('I', 'Interview')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
