# Generated by Django 5.0.2 on 2024-11-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_article_type_alter_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auther_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='auther_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
