# Generated by Django 5.0.2 on 2024-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_comment_auther_email_comment_auther_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='News.article'),
        ),
    ]
