# Generated by Django 5.0.2 on 2024-11-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_remove_comment_post_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
